//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2.Classifieds.Core.Impl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OlxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OlxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("U2.Classifieds.Core.Impl.OlxResources", typeof(OlxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.olx.ua/detskiy-mir/
        ///https://www.olx.ua/detskiy-mir/detskaya-mebel/
        ///https://www.olx.ua/detskiy-mir/detskaya-obuv/
        ///https://www.olx.ua/detskiy-mir/detskaya-odezhda/
        ///https://www.olx.ua/detskiy-mir/detskie-avtokresla/
        ///https://www.olx.ua/detskiy-mir/detskie-kolyaski/
        ///https://www.olx.ua/detskiy-mir/detskiy-transport/
        ///https://www.olx.ua/detskiy-mir/igrushki/
        ///https://www.olx.ua/detskiy-mir/kormlenie/
        ///https://www.olx.ua/detskiy-mir/prochie-detskie-tovary/
        ///https://www.olx.ua/detskiy-mir/tovary-dl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialBranches {
            get {
                return ResourceManager.GetString("InitialBranches", resourceCulture);
            }
        }
    }
}
